spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/debochichki/config-server
          search-paths: global/config
          default-label: master

server:
  port:
    8888
